import type { Metadata } from "next";
import "./globals.css";
import { LoadingProvider } from "./context/loadingContext";
import React from "react";
import Providers from "../../providers";
import GlobalLoading from "@/components/loadings/globalLoading";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
        <body>
        <Providers>
            <LoadingProvider>
                <GlobalLoading />
                {children}
            </LoadingProvider>
        </Providers>
        </body>
        </html>
    );
}
