import type { Metadata } from "next";
import "./globals.css";
import { LoadingProvider } from "./context/loadingContext";
import React from "react";
import Providers from "../../providers";
import GlobalLoading from "@/components/loadings/globalLoading";
import {Geist, Geist_Mono} from "next/font/google";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="vi" className={`${geistSans.variable} ${geistMono.variable}`}>
		<body>
		<Providers>
				{children}
		</Providers>
		</body>
		</html>
	);
}
